##########################
# Instance configuration #
##########################

server.port=8082


##########################
# Database configuration #
##########################

# You can specify the schema using the parameter currentSchema in the url (on postgresql above 9.4)
# create the schema before launching CVEDB
datasource.url=jdbc:postgresql://postgres:5432/highlight?currentSchema=cvedb
datasource.driver=org.postgresql.Driver
datasource.username=postgres
datasource.password=postgres


##########################
#   Mail configuration   #
##########################

# In production, admisnitrastor's email is 'support@casthighlight.com'
# administrator.mail=support@casthighlight.com
administrator.mail=change.me@castsoftware.com

# In production, no reply's email is 'no-reply@casthighlight.com'
noreply.mail=shared-mailer@company.com

spring.mail.host=smtp.company.com
spring.mail.username=shared-mailer@company.com
spring.mail.password=xxxxxx
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.port=25
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

##########################
#   API Key              #
##########################
nist.apiKey=CHANGEME-nist-api-key
